### PR TITLE
addressing issue #132

### PR DESCRIPTION
**Pull request by cmaceves**
addressing issue #132, allowing both forward and reverse primers to be trimmed from a strand if the primer pair file is passed using the experimental -f flag. issue raised for small insert sizes by a user.

### CODE REVIEW

**Comment by cmaceves** [comment]
for unpaired data, if a primer pair file is provided, we now use that information to determine which NT's to trim

**Comment by khyox** [comment]
Hi Chrissy, thank you so much for working on these important issues! Do you have an estimate of when you will be ready to merge your code changes? Are you thinking of a new version tag after this? Thank you very much!

**Comment by cmaceves** [comment]
Hi @khyox! We will be looking to bump versions after this merge. Review is still in progress, should be within the next few weeks

**Comment by khyox** [comment]
Thank you so much for your reply and for your work on the merge, Chrissy! We will be looking forward to it and the version bump.

**Pull request merged**
